spring.datasource.url=jdbc:postgresql://localhost:5432/chronos_db
spring.datasource.username=postgres
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# IMPORTANT
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

job.email.username = lmahajan367@gmail.com
job.email.password = zobl polk jgzo xpoo